### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by NaseBe** [NaseBe/protospace-35785#5]
# URL
https://protospace-35785.herokuapp.com/

**Comment by takumi0530** [comment]
@NaseBe さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by NaseBe** [comment]
@takumi0530 迅速な対応ありがとうございました！
